### ISSUE TITLE
Moon Phase

### ISSUE THREAD

**Issue by Jxid** [probonopd/TimeLord#2]
Can you please explain to me how i can get in serial monitor the moon phase at a certain date?
Thank you.

**Comment by probonopd** [comment]
https://github.com/probonopd/TimeLord/blob/ccfdceb37233fb613610582acfd4afd6894a99b1/TimeLord.cpp#L57

**Comment by Jxid** [comment]
Thank you.
I solved my problem.

**Comment by Jxid** [comment]
Is it possible to get moon phase in words and not in numbers?

**Comment by probonopd** [comment]
I think you need to find a way to do that yourself. Please note that I am not the author of this code, I just made a package out of it a couple of years ago.

**Comment by Jxid** [comment]
OK. Thank you.
