### ISSUE TITLE
Hacktoberfest 2021

### ISSUE THREAD

**Issue by SteveAmor** [probonopd/TimeLord#4]
Hi, thanks for the Arduio library. I have a few PRs I would like to raise and wondered if you would tag this repo for Hacktoberfest 2011.  Info available here:

A repository/project is considered to be participating in Hacktoberfest if the 'hacktoberfest' topic is present and is accepting public contributions via pull requests. An individual pull request can also be opted-in directly by adding the 'hacktoberfest-accepted' label.

A pull request is considered approved once it has an overall approving review from maintainers, or has been merged by maintainers, or has been given the 'hacktoberfest-accepted' label. A pull request with any label containing the word 'spam' or 'invalid' will be considered ineligible for Hacktoberfest.

[Hacktoberfest 2021](https://hacktoberfest.digitalocean.com/resources/participation)

**Comment by Mehul-Thuletiya** [comment]
Assign the issue to me. I will fix it

**Comment by probonopd** [comment]
Hello, please send your pull request and I will add the 'hacktoberfest-accepted' label to it if it can be merged. Thanks!

**Comment by SteveAmor** [comment]
Thanks!
